language: node_js
sudo: required
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
cache:
  yarn: true
after_success:
  - ls
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: "8.9.4"
      script: skip
      after_script:
        - yarn build
        - mkdir ./.nyc_output
        - ls
        - yarn coveralls
      # deploy:
      #   provider: script
      #   skip_cleanup: true
      #   after_deploy:
      #     - yarn build
      #     - git add . && git commit --no-verify -m \"dogfood for release\"
      #     - npx semantic-release
      #     - mkdir ./.nyc_output
      #     - yarn coveralls

