language: node_js
sudo: required
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
cache:
  yarn: true
jobs:
  include:
    - stage: release
      if: branch = master
      node_js:
        - "8.9.4"
      deploy:
        provider: script
        skip_cleanup: true
        before_deploy:
          - mkdir ./.nyc_output
          # - openssl aes-256-cbc -K $encrypted_dc2adf587a89_key -iv $encrypted_dc2adf587a89_iv -in .travis.secrets.tar.enc -out .travis.secrets.tar -d
          # - tar -xvf .travis.secrets.tar
          # - rm .travis.secrets.tar
          # - gpg --import travis.gpg
          # - rm travis.gpg
          # - mv settings.xml $HOME/.m2/settings.xml
        after_success:
          - yarn coveralls
        script: |
          yarn build &&
          git add . &&
          git commit --no-verify -m \"dogfood pre-release\" &&
          npx semantic-release
