language: node_js
sudo: required
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
cache:
  yarn: true
