#!/usr/bin/env node

const program = require('commander')

const { log } = require('../../')

program
  .option('-p, --pattern [pattern]', 'Glob pattern pointing to domain files', 'src/**/*.yml')
  .option('-t, --translator [translatorName]', 'Language translator (log|ubi|site|joi)', 'log')
  .option('--verbose', 'When activated shows text on cli')
  .parse(process.argv)

log(program)
