#!/usr/bin/env node

const program = require('commander')

const { save } = require('../../')

program
  .option('-p, --pattern [pattern]', 'Glob pattern pointing to domain files', 'src/**/*.yml')
  .option('-o, --output [output]', 'Output folder for source files', 'domain')
  .option('-s, --same-folder', 'Output folder is the same as domain file. Overides output flag')
  .option('-t, --translator [translatorName]', 'Language translator (log|ubi|site|joi)', 'log')
  .option('--verbose', 'When activated shows text on cli')
  .parse(process.argv)

save(program)
